### PR TITLE
implementing a search bar

### PR DESCRIPTION
**Pull request by HardwareConvert**
Please check if it works.

### CODE REVIEW

**Comment by kchia** [comment]
@HardwareConvert should this PR be merged? It's been open for 2 days.

**Comment by HardwareConvert** [comment]
Yes please and thank you.

**Comment by kchia** [comment]
@HardwareConvert you are responsible for getting somebody to approve and merge it.

**Comment by HardwareConvert** [comment]
Okay, will do.

**Comment by HardwareConvert** [comment]
I had already asked Joyce and Brittany, however no response since then.

I'll try Tatyana and/or Haji this time.

**Comment by kchia** [comment]
@HardwareConvert excellent!

**Comment by HardwareConvert** [comment]
Thank you!

**Pull request merged**
